---
# (Feel free to remove this in your own stylesheets)
# This file is used to store CSS variables.
# Any colors and code that works with CSS variables ["--var()"] will work
# Hence you see:
# - Colours: 'Color names', RGB Hex, RGB(), RGBA(), HSL(), HSLA()
#            [The "A" stands for Alpha/Transparancy]
# - Gradients: linear-gradient(), radial-gradient()
# - Background images: url(../img/noise.png)
#
# Most items with "Background" are literally used as: "background: var(--variableName);" in CSS
# -hover, -active, -checked etc are all literally used in something similar to: "button:hover {...background: var(--varName);}"
# and will only be used when that action is performed on that element.
#
# Comments are indicated with a "#" and are ignored by the program. Add/Remove them as you please.

# This theme's name (Shows in-app, can be different to filename)
name: Default

# Text selection styling
selectionColor: "#402B00"
selectionBackground: "#FFAA00"

# Right-Click context menu (Shows on account right-click)
contextMenuBackground: "#14151E"
contextMenuBackground-hover: "#1B2737"
contextMenuLeftBorder-hover: "#364E6E"
contextMenuTextColor: "#B0BEC5"
contextMenuTextColor-hover: "#FFFFFF"
contextMenuBoxShadow: none

# Headerbar at the top, with the account switcher's page title and window controls
headerbarBackground: "#14151E"
headerbarTCNOFill: white
windowControlsBackground-hover: rgba(255,255,255,0.1)
windowControlsBackground-active: rgba(255,255,255,0.2)
windowControlsCloseBackground: "#E81123"
windowControlsCloseBackground-active: "#F1707A"
windowTitleColor: white

# Footer at the bottom, with "Login" and "Add New" buttons
footerBackground: "#222"
footerColor: "#DDD"
# Icons
settingsIconFill: white
aboutIconFill: white

# Scrollbars, such as on the side
scrollbarTrackBackground: "#1F202D"
scrollbarThumbBackground: "#515164"
scrollbarThumbBackground-hover: "#555"

# Accounts
accountListItemWidth: 100px
accountListItemHeight: 135px
accountBackground-placeholder: "#28374E"
accountBorder-placeholder: '2px dashed #2777A4'
accountPColor: "#DDD"
accountColor: white
accountBackground-hover: "#28374E"
accountBackground-checked: "#274560"
accountBorder-hover: "#2777A4"
accountBorder-checked: "#26A0DA"
accountListBackground: 'url(../img/noise.png), linear-gradient(90deg, #2e2f42, #28293A 100%)'

# Application-wide settings
mainBackground: "#28293A"
defaultTextColor: white
linkColor: "#FFAA00"
linkColor-hover: "#FFDD00"
linkColor-active: "#CC7700"

# Items with borders
borderedItemBorderColor: "#888"
borderedItemBorderColor-focus: "#888"
borderedItemBorderColorBottom-focus: "#FFAA00"

# Input: Buttons
buttonBackground: "#333"
buttonBackground-active: "#222"
buttonBackground-hover: "#444"
buttonBorder: "#888"
buttonBorder-hover: "#888"
buttonBorder-active: "#FFAA00"
buttonColor: white

# Input: Checkboxes
checkboxBorder: white
checkboxBorder-checked: white
checkboxBackground: "#28293A"
checkboxBackground-checked: "#FFAA00"

# Input: Text
inputBackground: "#212529"
inputColor: white

# Input: Dropdown
dropdownBackground: "#333"
dropdownBorder: "#888"
dropdownColor: white
dropdownItemBackground-active: "#222"
dropdownItemBackground-hover: "#444"

# List (Such as the Forgotten Account list -> 'Checked' = selected)
listBackground: "#222"
listBackgroundColor-checked: "#FFAA00"
listColor: white
listColor-checked: white
listTextColor-before: "#FFAA00"
listTextColor-before-checked: "#945300"
listTextColor-after: "#3DFF89"
listTextColor-after-checked: "#945300"

# Settings: Section headers (The dividers with text)
settingsHeaderColor: white
settingsHeaderHrBorder: "#BBB"

# Modal: Popup (Info, selecting platform .exe location...)
modalBackground: "#00000055"
modalFgBackground: "#28293A"
modalInputBackground: "#212529"
modalTCNOFill: white
# Modal: Specific to finding files (Such as Steam's .exe)
foundColor: lime
foundBackground: green
notFoundColor: red
notFoundBackground: darkred

# Toast notifications
notification-color-dark-text: white
notification-color-dark-border: rgb(20, 20, 20)
notification-color-info: rgb(3, 169, 244)
notification-color-info-light: rgba(3, 169, 244, .25)
notification-color-info-lighter: "#17132C"
notification-color-success: rgb(76, 175, 80)
notification-color-success-light: rgba(76, 175, 80, .25)
notification-color-success-lighter: "#17132C"
notification-color-warning: rgb(255, 152, 0)
notification-color-warning-light: rgba(255, 152, 0, .25)
notification-color-warning-lighter: "#17132C"
notification-color-error: rgb(244, 67, 54)
notification-color-error-light: rgba(244, 67, 54, .25)
notification-color-error-lighter: "#17132C"

# Update notification headerbar
updateBarBackground: "#FFAA00"
updateBarColor: black

# ------------
# Platform specific options:
# ------------
# Steam
limited: yellow
vac: red
# Riot Games
leagueIcon: white
runeterraIcon: white
valorantIcon: white
