name: Public GitHub build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Public build'

jobs:

  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: dotnet restore

    # Build Debug
    - name: Build
      run: dotnet build TcNo-Acc-Switcher-Client\TcNo-Acc-Switcher-Client.csproj --configuration Debug
        
    # Build Debug
    - name: Build
      run: dotnet build TcNo-Acc-Switcher-Client\TcNo-Acc-Switcher-Client.csproj --configuration Release

    # Debug
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Debug
        path: TcNo-Acc-Switcher-Client\bin\Debug\net5.0-windows
        
    # Release
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Release
        path: TcNo-Acc-Switcher-Client\bin\Release\net5.0-windows
